apiVersion: v1
kind: Service
metadata:
  name: game-app-service
spec:
  selector:
    app: game-app
  ports:
    - protocol: TCP
      port: 3301
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app-deployment
spec:
  selector:
    matchLabels:
      app: game-app
  replicas: 1
  template:
    metadata:
      labels:
        app: game-app
    spec:
      containers:
        # GAME FRONTEND DEPLOYMENT
        - name: game-app-service
          image: ghcr.io/atos-reshape/game-app:staging
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "80"
      imagePullSecrets:
        - name: dockerconfigjson-github-com
