apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        # GATEWAY DEPLOYMENT
        - name: gateway
          image: ghcr.io/atos-reshape/api-gateway:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: FRONTEND_HOST
              value: game-app-service
            - name: FRONTEND_PORT
              value: "3301"
      imagePullSecrets:
        - name: dockerconfigjson-github-com
